# Generated by Django 4.2.17 on 2024-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.TextField(max_length=300)),
                ('genre', models.TextField(max_length=500)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to='image/')),
                ('audio_file', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
